import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readOnlySource } from "../scripts/read_only_source.mjs";
import { buildSourceReview, readOnlyReview } from "../scripts/export_review.mjs";
import { mkdtempSync, readFileSync, writeFileSync, statSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const require = createRequire(import.meta.url);
const ledger = require("../ledger-engine.js");
const history = require("../history-repository.js");
const copy = value => JSON.parse(JSON.stringify(value));
const prefix = "users/test-user/financeData/primary";
const at = "2026-09-11T05:00:00.000Z";
function fixture() {
  const events = [ledger.normalizeLedgerEvent({
    eventId: "opening-cash", type: "OPENING_BALANCE", balanceKind: "CASH",
    accountId: "cash-account", cashAccountId: "cash-account", cashAssetId: "cash-asset",
    tradeDate: "2026-09-01", amount: 1000, currency: "KRW", fxRate: 1
  }).event];
  const bundle = history.createHistoryBundle({
    snapshots: [{ id: "saved-1", createdAt: "2026-09-10T04:00:00.000Z", total: 1000,
      note: "private", typeTotals: { CASH: 1000 } }], performanceObservations: []
  }, { historyId: "history-test", updatedAt: "2026-09-10T04:00:00.000Z" });
  const { historyId, ...hm } = bundle.manifest;
  const primary = { path: prefix, updateTime: "2026-09-10T05:00:00.123456Z", data: {
    schemaVersion: 9, revision: 1, assets: [],
    ledgerMeta: { activeLedgerId: "ledger-test", eventCount: 1,
      eventFingerprint: ledger.fingerprintLedger(events), baselineDate: "2026-09-01" },
    historyMeta: { ...hm, activeHistoryId: historyId }
  } };
  return { primary, events, bundle };
}
function transportFor(f, options = {}) {
  const calls = [];
  let primaryReads = 0;
  return { calls, getDocument: async path => {
    calls.push(["get", path]);
    assert.equal(path, prefix);
    primaryReads += 1;
    return options.primary ? options.primary(primaryReads, copy(f.primary)) : copy(f.primary);
  }, listDocuments: async (path, page) => {
    calls.push(["list", path, page]);
    const items = path.endsWith("events") ? f.events.map(data => ({
      path: `${path}/${data.eventId}`, updateTime: f.primary.updateTime, data
    })) : f.bundle.chunks.map(data => ({ path: `${path}/${data.chunkId}`, updateTime: f.primary.updateTime, data }));
    return options.page ? options.page(path, page, copy(items)) : { documents: copy(items), nextPageToken: null };
  } };
}
const run = (f, options = {}, limits = {}) => readOnlySource({ transport: transportFor(f, options),
  uid: "test-user", observedAt: at, ...limits });

const f = fixture();
// Captured from origin/main app.js (361d7b4), not generated by this implementation.
assert.equal(ledger.fingerprintLedger([]), "cyrb128-v1:7fd001b7398370a22bd23760016d46a5");
assert.equal(ledger.fingerprintLedger(f.events), "cyrb128-v1:6290d57d5665cd4b96de4e79a9940d00");
const before = JSON.stringify(f);
const transport = transportFor(f);
const result = await readOnlySource({ transport, uid: "test-user", observedAt: at });
assert.equal(result.receipt.reads, 4);
assert.equal(result.receipt.writeCount, 0);
assert.equal(result.receipt.eventCount, 1);
assert.equal(result.receipt.snapshotCount, 1);
assert.equal(result.receipt.economicStateValidated, false);
assert.equal(result.receipt.latestValuationVerified, false);
assert.equal(result.receipt.stateDigest, history.digestCanonical(result.state));
assert.deepEqual(result.state.events, f.events);
assert.deepEqual(result.state.snapshots, history.restoreHistory(f.bundle).snapshots);
assert.equal(JSON.stringify(f), before);
assert.ok(transport.calls.every(([op]) => ["get", "list"].includes(op)));

const paged = fixture();
paged.events.push(ledger.normalizeLedgerEvent({ ...paged.events[0], eventId: "opening-other",
  accountId: "other-account", cashAccountId: "other-account", cashAssetId: "other-asset" }).event);
paged.primary.data.ledgerMeta.eventCount = 2;
paged.primary.data.ledgerMeta.eventFingerprint = ledger.fingerprintLedger(paged.events);
const pages = await run(paged, { page: (path, query, rows) => path.endsWith("events")
  ? { documents: query.pageToken ? rows.slice(1) : rows.slice(0, 1), nextPageToken: query.pageToken ? null : "second" }
  : { documents: rows, nextPageToken: null } });
assert.equal(pages.receipt.eventCount, 2);
assert.equal(pages.receipt.reads, 5);

// Full primary content and updateTime are checked even without a revision bump.
const retried = await run(f, { primary: (n, row) => {
  if (n >= 2) row.data.assets = [{ id: "changed" }];
  return row;
} });
assert.equal(retried.receipt.attempts, 2);
assert.deepEqual(retried.state.assets, [{ id: "changed" }]);
await assert.rejects(run(f, { primary: (n, row) => ({ ...row,
  updateTime: `2026-09-10T05:00:00.${String(n).padStart(6, "0")}Z` }) }), /SOURCE_STATE_MOVING/);
await assert.rejects(run(f, { primary: () => null }), /SOURCE_PRIMARY_MISSING/);
await assert.rejects(run(f, { primary: (_, row) => ({ ...row, path: "users/other/financeData/primary" }) }), /INVALID_SOURCE_DOCUMENT/);
await assert.rejects(run(f, { primary: (_, row) => ({ ...row, updateTime: "2026-09-12T00:00:00Z" }) }), /INVALID_SOURCE_DOCUMENT/);
await assert.rejects(run(f, {}, { uid: "../other" }), /INVALID_READ_ONLY_SOURCE_REQUEST/);
await assert.rejects(run(f, {}, { maxReads: 1 }), /SOURCE_READ_BUDGET_EXCEEDED/);
await assert.rejects(run(f, {}, { maxBytes: 10 }), /SOURCE_BYTE_BUDGET_EXCEEDED/);

const altered = fixture();
altered.events[0].amount = 2000;
await assert.rejects(run(altered), /SOURCE_LEDGER_FINGERPRINT_MISMATCH/);
const chunk = fixture();
chunk.bundle.chunks[0].items[0].total = 2000;
await assert.rejects(run(chunk), { code: "CHUNK_DIGEST_MISMATCH" });
await assert.rejects(run(f, { page: () => ({ documents: [], nextPageToken: null }) }), /SOURCE_DOCUMENT_COUNT_MISMATCH/);
await assert.rejects(run(f, { page: () => ({ documents: [], nextPageToken: "again" }) }), /SOURCE_PAGE_TOKEN_LOOP/);
await assert.rejects(run(f, { page: (_, __, rows) => ({
  documents: [{ ...rows[0], path: rows[0].path.replace("test-user", "other") }], nextPageToken: null
}) }), /INVALID_SOURCE_DOCUMENT/);
await assert.rejects(run(f, { page: (_, __, rows) => ({
  documents: [rows[0], rows[0]], nextPageToken: null
}) }), /DUPLICATE_SOURCE_DOCUMENT/);
await assert.rejects(readOnlySource({ uid: "test-user", observedAt: at,
  transport: { getDocument: async () => { throw new Error("AUTH_EXPIRED"); }, listDocuments: async () => {} }
}), /AUTH_EXPIRED/);

// The explicit inline v9 layout is supported; missing history is never invented.
const flat = fixture();
Object.assign(flat.primary.data, history.restoreHistory(flat.bundle));
delete flat.primary.data.historyMeta;
assert.equal((await run(flat)).receipt.reads, 3);
delete flat.primary.data.snapshots;
await assert.rejects(run(flat), /SOURCE_INLINE_HISTORY_MISSING/);
console.log("read-only source tests passed");

const exportFixture = fixture();
exportFixture.primary.data.retirement = { ...require("../retirement-engine.js").defaults };
const exportSource = await run(exportFixture);
const exportOptions = { generatedAt: at, producerCommit: "a".repeat(40) };
const exported = buildSourceReview(exportSource, exportOptions);
assert.equal(exported.receipt.sourceStateDigest, exportSource.receipt.stateDigest);
assert.equal(exported.receipt.sourceReceiptDigest, history.digestCanonical(exportSource.receipt));
assert.equal(exported.receipt.reviewDigest, exported.review.digest);
assert.equal(exported.receipt.currentAllocationEligible, false);
assert.equal(exported.receipt.authenticationVerifiedByBuilder, false);
assert.equal(exported.review.valuationStatus, "MISSING_LEGACY_SNAPSHOT_VALUATION");
const exportTransport = transportFor(exportFixture);
assert.deepEqual(await readOnlyReview({ transport: exportTransport, uid: "test-user", observedAt: at,
  ...exportOptions }), exported);
assert.equal(exportTransport.calls.length, 4);
for (const modify of [
  s => { s.state.retirement.currentAge = 40; },
  s => { s.receipt.eventCount += 1; },
  s => { s.state.events[0].amount = 2000; s.receipt.stateDigest = history.digestCanonical(s.state); },
  s => { s.receipt.economicStateValidated = true; },
  s => { s.receipt.observedAt = "2026-09-12T00:00:00.000Z"; },
  s => { s.state.schemaVersion = 8; s.receipt.stateDigest = history.digestCanonical(s.state); },
  s => { s.state.snapshots[0].createdAt = "2026-09-12T00:00:00.000Z";
    s.receipt.stateDigest = history.digestCanonical(s.state); }
]) {
  const damaged = copy(exportSource); modify(damaged);
  assert.throws(() => buildSourceReview(damaged, exportOptions), /INVALID_REVIEW/);
}
const noRead = transportFor(exportFixture);
await assert.rejects(readOnlyReview({ transport: noRead, uid: "test-user", observedAt: at,
  ...exportOptions, producerCommit: "invalid" }), /CONTEXT/);
assert.equal(noRead.calls.length, 0);
await assert.rejects(readOnlyReview({ transport: noRead, uid: "test-user", observedAt: at,
  ...exportOptions, timeZone: "INVALID" }), /CONTEXT/);
assert.equal(noRead.calls.length, 0);
const directory = mkdtempSync(join(tmpdir(), "assettrail-export-test-"));
try {
  const input = join(directory, "source.json"), output = join(directory, "review.json");
  writeFileSync(input, JSON.stringify(exportSource), { mode: 0o600 });
  const args = ["scripts/export_review.mjs", "--source", input, "--output", output,
    "--generated-at", at, "--producer-commit", exportOptions.producerCommit];
  const first = spawnSync(process.execPath, args, { encoding: "utf8" });
  assert.equal(first.status, 0, first.stderr);
  assert.deepEqual(JSON.parse(readFileSync(output, "utf8")), exported);
  assert.equal(statSync(output).mode & 0o777, 0o600);
  const bytes = readFileSync(output);
  const repeated = spawnSync(process.execPath, args, { encoding: "utf8" });
  assert.equal(repeated.status, 1);
  assert.equal(repeated.stderr, "ASSETTRAIL_EXPORT_FAILED\n");
  assert.deepEqual(readFileSync(output), bytes);
} finally { rmSync(directory, { recursive: true, force: true }); }
console.log("read-only V3 export: receipt binding, CLI and no-overwrite checks passed");
